version: '3.1'

services:
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=meow
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8080:8080